### ISSUE TITLE
Develop Solution Architecture Document template for submission to NICS

### ISSUE THREAD

**Issue by StephenPatterson-DSS** [dof-dss/architecture-team-repository#24]
This document should be completed by third parties when proposing changes to the NICS Architecture.

**Comment by dof-lestera** [comment]
First stab at this.  Probably needs a lot more work and reorganised.
[Solution Architecture Change Control.docx](https://github.com/dof-dss/architecture-team-repository/files/4394903/Solution.Architecture.Change.Control.docx)

**Comment by StephenPatterson-DSS** [comment]
This is a really good first draft. I'll try to put some time aside over the next few weeks to review. I'm going to move to the solution repository so we can version control the document.
